send_command:
  name: Set State
  description: Send media player state.
    entity:
      integration: ir_media_player_wrapper
      domain: media_player
  fields:
    state:
      name: State
      description: 'The desired state of the media player.'
      required: true
      selector:
        select:
          multiple: false
          options:
            - Off
            - On
            - Idle
            - Playing
            - Paused
            - Buffering
